# Setup
title:               Rombornoz
tagline:             'Un blog de Joaquín Romero'
#description:         ''
url:                 https://www.rombornoz.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Joaquín Romero
  url:               
  email:             

footer-links:
  linkedin:          https://www.linkedin.com/in/joarombornoz/

# Gems
plugins:
  - jekyll-paginate

# Custom vars
#version:             
#google_analytics_id: #UA-XXXX-Y
