# Setup
title:               Rombornoz
tagline:             'Un blog de Joaquín Romero'
description:         'Descripción toda piola'
url:                 https://www.rombornoz.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Joaquín Romero
  url:               https://www.linkedin.com/in/joarombornoz/
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
#version:             
#google_analytics_id: #UA-XXXX-Y
